export const logAction = {
  "CREATE": "CREATE",
  "DELETE": "DELETE",
  "GETLIST": "GETLIST",
  "GETONE": "GETONE",
  "GETMANY": "GETMANY",
  "GETMANYREFERENCE": "GETMANYREFERENCE",
  "UPDATE": "UPDATE",
  "UPDATEMANY":"UPDATEMANY",
  "DELETEMANY": "DELETEMANY"
}

// export const logAction = {
//   "CREATE_ADDRESS": "CREATE_ADDRESS",
//   "DELETE_ADDRESS": "DELETE_ADDRESS",
//   "GETLIST_ADDRESS": "GETLIST_ADDRESS",
//   "GETONE_ADDRESS": "GETONE_ADDRESS",
//   "GETMANY_ADDRESS": "GETMANY_ADDRESS",
//   "GETMANYREFERENCE_ADDRESS": "GETMANYREFERENCE_ADDRESS",
//   "UPDATE_ADDRESS": "UPDATE_ADDRESS",
//   "UPDATEMANY_ADDRESS":"UPDATEMANY_ADDRESS",
//   "DELETEMANY_ADDRESS": "DELETEMANY_ADDRESS",

//   "CREATE_LOG": "CREATE_LOG",
//   "DELETE_LOG": "DELETE_LOG",
//   "GETLIST_LOG": "GETLIST_LOG",
//   "GETONE_LOG": "GETONE_LOG",
//   "GETMANY_LOG": "GETMANY_LOG",
//   "GETMANYREFERENCE_LOG": "GETMANYREFERENCE_LOG",
//   "UPDATE_LOG": "UPDATE_LOG",
//   "UPDATEMANY_LOG":"UPDATEMANY_LOG",
//   "DELETEMANY_LOG": "DELETEMANY_LOG"
// }